---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.4
  name: web
  namespace: nodeapp
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: nuttsmare/node-hello-web:v0.0.2
        name: hellonode
