apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: nodeapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (10m)
      targetAverageUtilization: 99
